export default {
  divQuote: document.getElementById('result-quote'),
  getQuoteButton: document.getElementById('quote'),
  divCategories: document.getElementById('categories'),
  divCategoriesContainer: document.querySelector('.categories-container'),
  filtersRef: document.getElementById('filters'),
  divExercises: document.getElementById('exercises'),
  footerForm: document.querySelectorAll('.footer-form'),
  exTitel: document.querySelector('.exercises-title'),
  exSearch: document.getElementById('exercises-search'),
  divExSearch: document.getElementById('search-wrapper'),
  btnSearch: document.querySelector('.exercises-search-button'),
  exSearchImg: document.getElementById('search-img'),
  closeModalBtn: document.querySelector('.modal-close-btn'),
  modalMainRef: document.querySelector('.modal-main'),
  backdrop: document.querySelector('.backdrop'),
  modalContainer: document.querySelector('.modal-container'),
  addFavorite: document.querySelector('.add-to-favorites'),
  giveRating: document.querySelector('.give-a-rating'),
  favorites: document.querySelector('.favorites-list'),
  buttonTheme: document.querySelectorAll('.theme-switch'),
  body: document.querySelector('body'),
  sun: document.querySelectorAll('.sun'),
  moon: document.querySelectorAll('.moon'),
  modalMain: document.querySelector('.modal-main'),
};
