export default {
  //ці змінні як приклад для подальшого використання
  divQuote: document.getElementById('result-quote'),
  getQuoteButton: document.getElementById('quote'),
  divCategories: document.getElementById('categories'),
  filtersRef: document.getElementById('filters'),
  divExercises: document.getElementById('exercises'),
  footerForm: document.querySelectorAll('.footer-form'),
  exSearch: document.getElementById('exercises-search'),
  buttonTheme: document.getElementById('theme-switch'),
  body: document.querySelector('body'),
  heroTitle: document.querySelector('.hero-title'),
  heroSubTitle: document.querySelector('.hero-subtitle'),
  headerMediaLinks: document.querySelectorAll('.header-social-media-link'),
  headerMediaLinksIcons: document.querySelectorAll('.header-social-media-icon'),
  logoIcon: document.querySelector('.social-media-icon'),
  heroTitleIcon: document.querySelector('.hero-title-icon'),
  heroHashtagIcon: document.querySelectorAll('.hero-hashtag-item'),
  headerNavBar: document.querySelector('.header-nav-list'),
  paginationButton: document.getElementById('tui-pagination-container'),
};
