import 'izitoast/dist/css/iziToast.min.css';
import './js/filters.js';
import './js/quote.js';
import './js/components/';
import './js/footer.js'
import './js/scroll-up.js';
import './js/header.js';
import './js/burger-menu.js';
import './js/pagination.js';